# general:
techdata_dir: 'data/tech/basic/'
techdata_files:
- cement
- other_industries
- steel
- steel_dri
projects_file: 'config/projects.xlsx'
start_year: 2022
end_year: 2045
ccfd_duration: 15
default_wacc: 0.06

# scenarios:
scenarios_dir: 'data/scenarios/basic/'
scenarios_actual:
  free_allocations: 'Joint product benchmarks, new technologies affect benchmark, incl. CBAM'
  prices:
    CO2: 'KSV-Base-CO2'
    Natural Gas: 'KSV-Base-Erdgas'
    Electricity: 'KSV-Base-Strom'
    Hydrogen: 'ISI: best-guess'
    Coking Coal: 'KSV-Base-Kohle'
    Injection Coal: 'Einblaskohle a)'
    Iron Ore: 'Eisenerz Agora'
    Scrap Steel: 'Zero_Dummy_Scrap'
    DRI-Pellets: 'DRI-Pellets Agora'
    Naphta: 'Naphta a)'
scenarios_bidding:
  free_allocations: 'Joint product benchmarks, new technologies affect benchmark, incl. CBAM'
  prices:
    CO2: 'KSV-Base-CO2'
    Natural Gas: 'KSV-Base-Erdgas'
    Electricity: 'KSV-Base-Strom'
    Hydrogen: 'ISI: best-guess'
    Coking Coal: 'KSV-Base-Kohle'
    Injection Coal: 'Einblaskohle a)'
    Iron Ore: 'Eisenerz Agora'
    Scrap Steel: 'Zero_Dummy_Scrap'
    DRI-Pellets: 'DRI-Pellets Agora'
    Naphta: 'Naphta a)'


# auction:
auction_type: 'price_based'
rest_budget_treatment: 'do not fill'
include_negative_payout_projects: True
criteria_weighting:
  cost_efficiency: 0.7
  relative_emission_reduction: 0.15
  energy_efficiency: 0.15
budget_cap_parameters:
  alpha: 0.2
  min_co2_price: 30.
auction_rounds:
- name: 'Call 1 (1/2023)'
  year: 2023
  budget_MEUR: 3.0
- name: 'Call 2 (2/2023)'
  year: 2023
  budget_MEUR: 3.0
- name: 'Call 3 (1/2024)'
  year: 2024
  budget_MEUR: 4.0
- name: 'Call 4 (2/2024)'
  year: 2024
  budget_MEUR: 4.0
- name: 'Call 5 (1/2025)'
  year: 2025
  budget_MEUR: 5.0
- name: 'Call 6 (2/2025)'
  year: 2025
  budget_MEUR: 5.0