# general:
mode: auction
techdata_dir: 'data/tech/basic/'
techdata_files:
- basic_chemicals
- cement
- glass_and_ceramics
- other_industries
- steel
- steel_dri
projects_file: 'config/projects.csv'
do_overwrite_project_start_year: False
ccfd_duration: 15
default_wacc: 0.06

#output
show_figures: True
show_figs_in_browser: True
output_dir: 'output/'
save_figures: False
crop_figures: True

# scenarios:
scenarios_dir: 'data/scenarios/basic/'
scenarios_actual:
  free_allocations: ''
  prices:
    Electricity: '100 steady'
    CO2: 'PIKExpertGuess-CO2'
    Natural Gas: '40 steady'
    Hydrogen: 'PIKExpertGuess-H2'
    Coking Coal: '100 steady'
    Injection Coal: '70 steady'
    Iron Ore: 'Eisenerz Agora'
    Scrap Steel: 'Zero_Dummy_Scrap'
    DRI-Pellets: 'DRI-Pellets Agora'
    Naphta: 'Naphta a)'
scenarios_bidding:
  free_allocations: ''
  prices:
    Electricity: '100 steady'
    CO2: 'PIKExpertGuess-CO2'
    Natural Gas: '40 steady'
    Hydrogen: 'PIKExpertGuess-H2'
    Coking Coal: '100 steady'
    Injection Coal: '70 steady'
    Iron Ore: 'Eisenerz Agora'
    Scrap Steel: 'Zero_Dummy_Scrap'
    DRI-Pellets: 'DRI-Pellets Agora'
    Naphta: 'Naphta a)'


# auction:
auction_round_default:
  budget_cap_co2_price_scen: 'Low-CO2'
  budget_cap_alpha: 0.2
  strike_price_a: 0.5
  rel_em_red_rr: 0.5
  rel_em_red_s: 0.2
auction_rounds:
- name: 'Call 1 (1/2023)'
  year: 2023
  budget_BnEUR: 3.0
- name: 'Call 2 (2/2023)'
  year: 2023
  budget_BnEUR: 3.0
- name: 'Call 3 (1/2024)'
  year: 2024
  budget_BnEUR: 4.0
- name: 'Call 4 (2/2024)'
  year: 2024
  budget_BnEUR: 4.0
- name: 'Call 5 (1/2025)'
  year: 2025
  budget_BnEUR: 5.0
- name: 'Call 6 (2/2025)'
  year: 2025
  budget_BnEUR: 5.0
